### ISSUE TITLE
Smartdown is crashing Craft somehow??

### ISSUE THREAD

**Issue by laurend** [monooso/smartdown.craft-plugin#1]
FYI, i just tried enabling this on a brand-new, up-to-date Craft install. It made my entire site go 'down' when I tried to enable it, as in all admin and public pages render as empty white pages. Removing the Smartdown files from my plugin directory resolved the issue. I tried re-downloading and re-adding files back into the dir and the same thing happened. I've since tried installing other third party plugins... no problem. 

Not sure if anyone else has run into this, as I've used this in the past without issues.

**Comment by monooso** [comment]
Hi Lauren,

What version of PHP are you running? SmartDown requires PHP 5.4 (which I should have made clear in the README, sorry).

Stephen

**Comment by monooso** [comment]
Added "requirements" note to README (ef3401bb605721117265c0ca0f3e3c5fed230e62).

**Comment by kamicrafted** [comment]
thanks for working on this to help fill the gaps in terms of better coverage for markdown in craft.
i've run into a similar issue as @laurend and am currently on php 5.5.9. 

trying to use the smartdown filter (for example {{ entry.body | smartdown }}) will break the page and no content will load. 

any ideas on what would be causing this? i'm looking for a solution to help with rendering fenced code blocks and this seemed to be exactly it. now if i only i could get it to work i'd be a happy camper... ;)

**Comment by monooso** [comment]
Are there any errors in Craft's log files (`/craft/storage/runtime/logs`)?

**Comment by kamicrafted** [comment]
just checked and it looks like nothing is being captured in the logs, unfortunately. i tried using a non-existent filter which did give me an error, whereas smartdown still renders the page partially up to the point where smartdown is being used. sorry i don't have much more information to provide.

**Comment by monooso** [comment]
Does SmartDown work at all on your site? For example, if you put the following in a blank template, does it output two paragraphs as expected?

~~~~~twig
{% set testContent %}
Pink, pink, well what's wrong with pink?

Seems like you've got a pink kink in your think.
{% endset %}

{{ testContent | smartdown }}
~~~~~

**Comment by kamicrafted** [comment]
tried that out and nothing shows up :disappointed:

**Comment by monooso** [comment]
Is it possible for you to give me shell access to the server? Without any logs or error messages to go on, I don't really have a way of debugging this.

If yes, you can email me at support [at] experiencehq [dot] net.

**Comment by monooso** [comment]
Failing that, admin access to the control panel would be a decent start.

**Comment by monooso** [comment]
Closing this for now, due to lack of feedback.

**Comment by laurend** [comment]
@monooso... funny thing. I totally forgot about this thread. For some reason I was never notified that you had responded several months ago so I'm sorry that Ieft you hanging there. Now I'm working on a new project, went to use this plugin and the same thing happened. I stumbled upon this and thought it was funny that I opened the original issue in the first place. 

Anyway, one interesting thing is that now I"m running my project both locally and on the live server from the same DB. The plugin files are in both locations. It seems to work fine when accessed locally (using MAMP). But when I try to access any part of my site remotely -- even the admin area -- the whole thing is blank after just enabling the plugin. I hadn't yet applied it to any templates. So I'm guessing the problem must be something to do with the remote environment.

I'm attaching what's appearing in the error log here. Hopefully you can shed some light on the issue.

```
******************************************************************************************************
2015/11/03 20:21:55 [error] [exception.Craft\HttpException.404] exception 'Craft\HttpException' in /chroot/home/pandlmed/lfab.nyc/craft/app/controllers/TemplatesController.php:59
Stack trace:
#0 [internal function]: Craft\TemplatesController->actionRender('homepage', Array)
#1 /chroot/home/pandlmed/lfab.nyc/craft/app/framework/web/actions/CAction.php(109): ReflectionMethod->invokeArgs(Object(Craft\TemplatesController), Array)
#2 /chroot/home/pandlmed/lfab.nyc/craft/app/framework/web/actions/CInlineAction.php(47): CAction->runWithParamsInternal(Object(Craft\TemplatesController), Object(ReflectionMethod), Array)
#3 /chroot/home/pandlmed/lfab.nyc/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /chroot/home/pandlmed/lfab.nyc/craft/app/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /chroot/home/pandlmed/lfab.nyc/craft/app/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /chroot/home/pandlmed/lfab.nyc/craft/app/framework/web/CWebApplication.php(282): CController->run('render')
#7 /chroot/home/pandlmed/lfab.nyc/craft/app/framework/web/CWebApplication.php(141): CWebApplication->runController('templates/rende...')
#8 /chroot/home/pandlmed/lfab.nyc/craft/app/etc/web/WebApp.php(278): CWebApplication->processRequest()
#9 /chroot/home/pandlmed/lfab.nyc/craft/app/framework/base/CApplication.php(184): Craft\WebApp->processRequest()
#10 /chroot/home/pandlmed/lfab.nyc/craft/app/index.php(62): CApplication->run()
#11 /chroot/home/pandlmed/lfab.nyc/html/index.php(19): require_once('/chroot/home/pa...')
#12 {main}
REQUEST_URI=/
---
2015/11/03 20:21:55 [error] [application] 
```

**Comment by monooso** [comment]
@laurend Could this be a permissions issue? Line 11 looks to be the root cause of the problem, but the `require_once` statement is truncated, so I can't tell which file it's attempting to load.

**Comment by monooso** [comment]
Closing this, due to a lack of feedback.
