### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by kerns** [monooso/smartdown.craft-plugin#3]
`Fatal error: Class 'Michelf\SmartyPants' not found in /path/to/craft/plugins/smartdown/SmartdownPlugin.php on line 106`

I've installed/enabled the plugin in the latest version of Craft (2.6.2776), and am getting this result when trying to use the filter. PHP Version is 5.5.20

**Comment by monooso** [comment]
Hi @kerns,

That sounds an awful lot like issue #2, but that was fixed a few months back. Do you have the most up-to-date version of Smartdown?

Stephen

**Comment by ogilv** [comment]
Same here with current github release. The folder is indeed still empty in the current master branch.

**Comment by monooso** [comment]
@ogilv / @kerns 

There seems to be some confusion here. If you just want to use the plugin you should to download [the latest _release_][release].

[release]: https://github.com/monooso/smartdown.craft-plugin/releases

You should only clone the repository (or download a zip of the repo files) if you wish to contribute code to the plugin.

Does that clarify things, and solve the issue?

Stephen

**Comment by ogilv** [comment]
Yes, indeed… thank you!  
Sorry for the misunderstanding – release 2.0.1, as linked to in your post above, installs without any issues.

**Comment by monooso** [comment]
@ogilv Cool, glad you got it sorted. I'll add a note to the README, to clarify things.

@kerns Does this also solve your problem?

**Comment by monooso** [comment]
Closing, due to lack of feedback.
