### ISSUE TITLE
{{ entry | smartdown }} does not work

### ISSUE THREAD

**Issue by fschroiff** [monooso/smartdown.craft-plugin#4]
`{{entry | smartdown}}` displays nothing. `{{entry.title | smartdown}}` displays the smartdowned title. 

As `{{ entry }}` displays the title of an entry I would expect `{{entry | smartdown}}` to work as well.

**Comment by monooso** [comment]
Hi Florian,

Thanks for the suggestion, but I won't be implementing this behaviour. Below is some background information, and my reasoning, in case you're interested.

`{{ entry }}` outputs the title, thanks to PHP's `__toString` magic method, which is called when you attempt to use the `entry` object as a string.

Smartdown explicitly checks that it has been passed a string before attempting any parsing, to guard against unexpected input. This means the automatic type coercion never occurs.

Whilst it is theoretically possible for me to implement support for this behaviour, I don't think the additional complexity (and therefore opportunity for bugs) is justified, particularly as the current fix (using `entry.title`) is so simple.

Stephen

**Comment by fschroiff** [comment]
Fair enough 👍
